name: example-firefox
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  firefox:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Firefox
        uses: cypress-io/github-action@v5
        timeout-minutes: 3
        with:
          build: npx cypress info
          browser: firefox

      - uses: actions/upload-artifact@v3
        with:
          name: screenshots-in-firefox
          path: cypress/
